/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gab_test_ndktasklist_Core */

#ifndef _Included_com_gab_test_ndktasklist_Core
#define _Included_com_gab_test_ndktasklist_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gab_test_ndktasklist_Core
 * Method:    getNmbTasks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gab_test_ndktasklist_Core_getNmbTasks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
