/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gab_test_ndktasklist_TaskMgr */

#ifndef _Included_com_gab_test_ndktasklist_TaskMgr
#define _Included_com_gab_test_ndktasklist_TaskMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gab_test_ndktasklist_TaskMgr
 * Method:    getNmbTasks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gab_test_ndktasklist_TaskMgr_getNmbTasks
  (JNIEnv *, jclass);

/*
 * Class:     com_gab_test_ndktasklist_TaskMgr
 * Method:    addTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gab_test_ndktasklist_TaskMgr_addTask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gab_test_ndktasklist_TaskMgr
 * Method:    getTask
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gab_test_ndktasklist_TaskMgr_getTask
  (JNIEnv *, jclass, jint);

///*
// * Class:     com_gab_test_ndktasklist_TaskMgr
// * Method:    getTasks
// * Signature: (II)[Ljava/lang/String;
// */
//JNIEXPORT jobjectArray JNICALL Java_com_gab_test_ndktasklist_TaskMgr_getTasks
//  (JNIEnv *, jclass, jint, jint);
//
///*
// * Class:     com_gab_test_ndktasklist_TaskMgr
// * Method:    addTasks
// * Signature: ([Ljava/lang/String;)V
// */
//JNIEXPORT void JNICALL Java_com_gab_test_ndktasklist_TaskMgr_addTasks
//  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_gab_test_ndktasklist_TaskMgr
 * Method:    initAndroidTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gab_test_ndktasklist_TaskMgr_initAndroidTask
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
